pipeline {
  agent any

  environment {
    GHCR_REPO        = "ghcr.io/eliozo/date-app"
    K8S_NAMESPACE    = "default"
    K8S_MANIFEST_DIR = "k8s"
    KUBECONFIG       = "/var/jenkins_home/.kube/config"
    DEPLOYMENT_NAME  = "date-app"
    CONTAINER_NAME   = "date-app"

    GIT_SSH_URL      = "git@github.com:eliozo/date-app.git"
    GIT_SSH_CRED_ID  = "github-ssh"
    ALLOWED_BRANCH   = "main"
  }

  stages {
    stage('Checkout (SSH, main only)') {
      steps {
        sshagent(credentials: [env.GIT_SSH_CRED_ID]) {
          sh '''
            mkdir -p ~/.ssh
            chmod 700 ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            chmod 600 ~/.ssh/known_hosts
          '''

          checkout([
            $class: 'GitSCM',
            branches: [[name: "*/${env.ALLOWED_BRANCH}"]],
            userRemoteConfigs: [[
              url: env.GIT_SSH_URL,
              credentialsId: env.GIT_SSH_CRED_ID
            ]]
          ])
        }

        sh 'git rev-parse --short HEAD > .git/shortsha'
      }
    }

    stage('Build Docker image') {
      steps {
        script { env.IMAGE_TAG = readFile('.git/shortsha').trim() }
        sh """
          docker build -t ${GHCR_REPO}:${IMAGE_TAG} .
          docker tag ${GHCR_REPO}:${IMAGE_TAG} ${GHCR_REPO}:latest
        """
      }
    }

    stage('Push to GHCR') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'ghrc-creds',
          usernameVariable: 'GH_USER',
          passwordVariable: 'GH_TOKEN'
        )]) {
          sh '''
            echo "${GH_TOKEN}" | docker login ghcr.io -u "${GH_USER}" --password-stdin
            docker push ${GHCR_REPO}:${IMAGE_TAG}
            docker push ${GHCR_REPO}:latest
            docker logout ghcr.io
          '''
        }
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh """
          kubectl -n ${K8S_NAMESPACE} apply -f ${K8S_MANIFEST_DIR}
          kubectl -n ${K8S_NAMESPACE} set image deployment/${DEPLOYMENT_NAME} \
            ${CONTAINER_NAME}=${GHCR_REPO}:${IMAGE_TAG}
          kubectl -n ${K8S_NAMESPACE} rollout status deployment/${DEPLOYMENT_NAME}
        """
      }
    }
  }
}